name: devfin_ui_kit
description: 'DevFin UI Kit'

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  go_router: ^12.1.3
  floating_draggable_widget: ^2.1.4
  flutter:
    sdk: flutter
  fl_chart: ^0.65.0
  flutter_svg: ^2.0.9
  url_launcher: ^6.2.2
  flutter_native_splash: ^2.3.8
  scrollable_positioned_list: ^0.3.8
  scroll_to_index: ^3.0.1
  visibility_detector: ^0.4.0+2
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_gen:
  output: lib/app/config/gen/

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/images/devfin_launcher.png'
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true

flutter_native_splash:
  color: '#001c27'
  image: assets/images/devfin_launcher.png
  android: true
  ios: true
